### ISSUE TITLE
429 Client Error: Too Many Requests for url

### ISSUE THREAD

**Issue by kitchmen** [sotolko/csgo-market-sniper#22]
Hi I run the program and then I get hit with a stop due to 

Traceback (most recent call last):
  File "C:\Users\kitch\Documents\GitHub\csgo-market-sniper\csgo-market-sniper.py", line 31, in <module>
    check_whole_page(count, url_info)
  File "C:\Users\kitch\Documents\GitHub\csgo-market-sniper\functions.py", line 159, in check_whole_page
    item_name, item_float, item_pattern, whole_json = save_json_response(btn)
  File "C:\Users\kitch\Documents\GitHub\csgo-market-sniper\functions.py", line 202, in save_json_response
    response.raise_for_status()
  File "C:\Users\kitch\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.csgofloat.com/?url=steam://rungame/730/76561202255233023/+csgo_econ_action_preview%20M4313927967666358717A29862318717D2315455664352767148

Could this be to the new issues with Steam restricting floatdb to so many inspects?

**Comment by DqRN** [comment]
yes

**Comment by TIllAd** [comment]
same error. Is there a fix?

**Comment by DqRN** [comment]
negative, either we wait for the api to sort its shit out or someone/the dev figures out another way to read floats and pattern ids

**Comment by jcardama** [comment]
Until the CSGOFloat api is fixed, what I've done is modified the script to install the CSGOFloat market checker extension and use the data provided by it to query for the float and paint seed.

**Comment by DqRN** [comment]
Huh my idea actually works haha

**Comment by DqRN** [comment]
@jcardama do you plan to share it?

**Comment by jcardama** [comment]
> Huh my idea actually works haha

It does, the only caveat is that the only information you can gather is Float & Paint Seed, no way on getting number of stickers or other information. Also had to add a bit of a delay as sometimes the extension takes a couple of seconds to load the float information so it takes more time to go through all the skins.

**Comment by DqRN** [comment]
> > Huh my idea actually works haha
> 
> It does, the only caveat is that the only information you can gather is Float & Paint Seed, no way on getting number of stickers or other information. Also had to add a bit of a delay as sometimes the extension takes a couple of seconds to load the float information so it takes more time to go through all the skins.

Sick, I mean at least it works :] do you plan to share it?

**Comment by jcardama** [comment]
> @jcardama do you plan to share it?

Indeed! Just making sure I didn't break anything in the process as I had to rewrite a bunch of the original script.

**Comment by DqRN** [comment]
> > @jcardama do you plan to share it?
> 
> Indeed! Just making sure I didn't break anything in the process as I had to rewrite a bunch of the original script.

How does that work does it update here or do you make your own project?

**Comment by jcardama** [comment]
> > > @jcardama do you plan to share it?
> > 
> > 
> > Indeed! Just making sure I didn't break anything in the process as I had to rewrite a bunch of the original script.
> 
> How does that work does it update here or do you make your own project?

Planning on creating a fork of this repo as, as you require to have the CSGOFloat Market Checker extension locally, will provide all the details on how to get it.

**Comment by kitchmen** [comment]
> > > > @jcardama do you plan to share it?
> > > 
> > > 
> > > Indeed! Just making sure I didn't break anything in the process as I had to rewrite a bunch of the original script.
> > 
> > 
> > How does that work does it update here or do you make your own project?
> 
> Planning on creating a fork of this repo as, as you require to have the CSGOFloat Market Checker extension locally, will provide all the details on how to get it.

Any idea on when you're gonna release it?  I can help test if need be.

**Comment by jcardama** [comment]
I've forked this repo and updated the bot to be able to use the CSGOFloat extension to get skin floats & patterns so the bot can function properly. [https://github.com/jcardama/csgo-market-sniper](https://github.com/jcardama/csgo-market-sniper)

**Comment by DqRN** [comment]
@jcardama idk what ive done haha 

![image](https://user-images.githubusercontent.com/105587614/235833520-b43e4389-2e36-42dc-9a26-390b4d57c079.png)

**Comment by jcardama** [comment]
> @jcardama idk what ive done haha
> 
> ![image](https://user-images.githubusercontent.com/105587614/235833520-b43e4389-2e36-42dc-9a26-390b4d57c079.png)

Make sure the path is surrounded by single quotes like this: `chrome_options.add_extension('C:\pah\to\extension.crx')`

**Comment by DqRN** [comment]
oop

**Comment by DqRN** [comment]
oop
![image](https://user-images.githubusercontent.com/105587614/235834153-549ca7a5-03e1-4017-a09d-8684074cb182.png)

**Comment by DqRN** [comment]
@jcardama it seems stops after its finished scanning all the desired skins

**Comment by jcardama** [comment]
> oop ![image](https://user-images.githubusercontent.com/105587614/235834153-549ca7a5-03e1-4017-a09d-8684074cb182.png)

Please update to latest version, I've commited a few changes to address some issues. Run the following command to get the latest changes: `git pull`

I'm currently testing with 14 skins and seems to be working fine.

**Comment by DqRN** [comment]
cleaner, but the same thing happened after scanning all the skins
![image](https://user-images.githubusercontent.com/105587614/235835994-c5dd836d-0655-43c3-b067-29d986b40b0f.png)

**Comment by DqRN** [comment]
hold up im dumb, its calling for the price in the config, but I still have (number_of_stickers:) so its pulling from the wrong line xD

Edit: I tested that theory and I was wrong its still doing it -__-

**Comment by jcardama** [comment]
> hold up im dumb, its calling for the price in the config, but I still have (number_of_stickers:) so its pulling from the wrong line xD

No worries, my bad for not mentioning you had to remove that. Still please pull again, I've added a potential fix even if it is incorrect..

**Comment by DqRN** [comment]
working fine now thanks

**Comment by DqRN** [comment]
@jcardama here is a new one for you, works fine after restarting it though.

![UoauA7NIJT](https://user-images.githubusercontent.com/105587614/235849290-e562de39-7723-473c-b101-4ef2dd9a22e8.png)

**Comment by kitchmen** [comment]
> @jcardama here is a new one for you, works fine after restarting it though.
> 
> ![UoauA7NIJT](https://user-images.githubusercontent.com/105587614/235849290-e562de39-7723-473c-b101-4ef2dd9a22e8.png)

I added a VPN and its been working fine for about an hour.

**Comment by jcardama** [comment]
> @jcardama here is a new one for you, works fine after restarting it though.
> 
> ![UoauA7NIJT](https://user-images.githubusercontent.com/105587614/235849290-e562de39-7723-473c-b101-4ef2dd9a22e8.png)

This issue is when trying to retrieve the sort button. I've made it so that it clicks it sorting floats from lower to highest, making it so that you don't have to go through all the pages to find the skins with the lower floats, making the bot more efficient. I've pushed a fix so if it doesn't find the button on time the bot can still continue.

@DqRN In the future please report any issues on the forked repo so we don't clutter this comment section.

**Comment by Cheezy1234** [comment]
@jcardama i am getting this issue where the buy button cant be found, is that because the skin has already sold or is another issue? 
![image](https://user-images.githubusercontent.com/131748333/236044178-b6e50598-e0c5-4d50-907d-7d552edd84de.png)

**Comment by jcardama** [comment]
> @jcardama i am getting this issue where the buy button cant be found, is that because the skin has already sold or is another issue? ![image](https://user-images.githubusercontent.com/131748333/236044178-b6e50598-e0c5-4d50-907d-7d552edd84de.png)

I'd check that the skin is not already sold, or when you get the error, check the actual listings, see if you can spot if the buy button is present.

**Comment by DqRN** [comment]
@jcardama yo I just tested the bot with a cheap item, set the listed patterns and it didn't buy anything :<

Edit: tested multiple pages, you can see the pattern ids on the browser but no buy is being executed

**Comment by jcardama** [comment]
> @jcardama yo I just tested the bot with a cheap item, set the listed patterns and it didn't buy anything :<
> 
> Edit: tested multiple pages, you can see the pattern ids on the browser but no buy is being executed

I've pushed an update that fixes the Pattern validation, could you verify?

I've enabled issues on the forked repo, please report any issues here: https://github.com/jcardama/csgo-market-sniper/issues

**Comment by DqRN** [comment]
@jcardama its working

**Comment by mszansan** [comment]
i have a problem while trying to install selenium-wire (i have every other from requirements.txt).
Collecting zstandard>=0.14.1 (from selenium-wire)                                                                                                                                                                                              Using cached zstandard-0.21.0.tar.gz (659 kB)                                                                                                                                                                                                Installing build dependencies ... done                                                                                                                                                                                                       Getting requirements to build wheel ... error                                                                                                                                                                                                error: subprocess-exited-with-error                                                                                                                                                                                                                                                                                                                                                                                                                                                       × Getting requirements to build wheel did not run successfully.                                                                                                                                                                              │ exit code: 1                                                                                                                                                                                                                               ╰─> [30 lines of output]                                                                                                                                                                                                                         Traceback (most recent call last):                                                                                                                                                                                                             File "C:\Users\PC\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>                                                                                     main()                                                                                                                                                                                                                                     File "C:\Users\PC\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main                                                                                         json_out['return_val'] = hook(**hook_input['kwargs'])                                                                                                                                                                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                                                      File "C:\Users\PC\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel                                                                 return hook(config_settings)                                                                                                                                                                                                                        ^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                                                                               File "C:\Users\PC\AppData\Local\Temp\pip-build-env-5fd0jznv\overlay\Lib\site-packages\setuptools\build_meta.py", line 355, in get_requires_for_build_wheel                                                                                     return self._get_build_requires(config_settings, requirements=['wheel'])                                                                                                                                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                                   File "C:\Users\PC\AppData\Local\Temp\pip-build-env-5fd0jznv\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in _get_build_requires                                                                                              self.run_setup()                                                                                                                                                                                                                           File "C:\Users\PC\AppData\Local\Temp\pip-build-env-5fd0jznv\overlay\Lib\site-packages\setuptools\build_meta.py", line 507, in run_setup                                                                                                        super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)                                                                                                                                                                  File "C:\Users\PC\AppData\Local\Temp\pip-build-env-5fd0jznv\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in run_setup                                                                                                        exec(code, locals())                                                                                                                                                                                                                       File "<string>", line 90, in <module>                                                                                                                                                                                                        File "C:\Users\PC\AppData\Local\Temp\pip-install-x6h7lq5r\zstandard_b460ea1ac66c4af3a9ed041980c64260\setup_zstd.py", line 66, in get_c_extension                                                                                               compiler.initialize()                                                                                                                                                                                                                      File "C:\Users\PC\AppData\Local\Temp\pip-build-env-5fd0jznv\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 253, in initialize                                                                                         vc_env = _get_vc_env(plat_spec)                                                                                                                                                                                                                       ^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                                                                            File "C:\Users\PC\AppData\Local\Temp\pip-build-env-5fd0jznv\overlay\Lib\site-packages\setuptools\msvc.py", line 233, in msvc14_get_vc_env                                                                                                      return _msvc14_get_vc_env(plat_spec)                                                                                                                                                                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                                                                       File "C:\Users\PC\AppData\Local\Temp\pip-build-env-5fd0jznv\overlay\Lib\site-packages\setuptools\msvc.py", line 190, in _msvc14_get_vc_env                                                                                                     raise distutils.errors.DistutilsPlatformError("Unable to find vcvarsall.bat")                                                                                                                                                            distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/                                               [end of output]                                                                                                                                                                                                                                                                                                                                                                                                                                                                       note: This error originates from a subprocess, and is likely not a problem with pip.                                                                                                                                                       error: subprocess-exited-with-error                                                                                                                                                                                                                                                                                                                                                                                                                                                       × Getting requirements to build wheel did not run successfully.                                                                                                                                                                              │ exit code: 1                                                                                                                                                                                                                               ╰─> See above for output.                                                                                                                                                                                                                                                                                                                                                                                                                                                                 note: This error originates from a subprocess, and is likely not a problem with pip.

could u help me?
